const Productdetail = [
  {
    id: 1,
    Title: 'Galaxy Tab S6 Lite 10.4-inch Android Tablet 128GB.',
    Cat: 'Tablet',
    Price: '723',
    Img: './assets/tp1.jpg',
  },
  {
    id: 2,
    Title: 'Tracker with IP67 Waterproof Pedometer Smart watch.',
    Cat: 'Smart Watch',
    Price: '168',
    Img: './assets/tp2.jpg',
  },
  {
    id: 3,
    Title: 'Cancelling Headphones Wireless.',
    Cat: 'Headphone',
    Price: '49',
    Img: './assets/tp3.jpg',
  },
  {
    id: 4,
    Title: 'Professional Camera 4K Digital Video Camera.',
    Cat: 'Camera',
    Price: '1049',
    Img: './assets/tp4.jpg',
  },
  {
    id: 5,
    Title: 'Mini Portable PD 22.5W Fast Charging Powerbank.',
    Cat: 'Powerbank',
    Price: '49',
    Img: './assets/tp5.jpg',
  },
  {
    id: 6,
    Title: 'CPU Cooler 2 Heat Pipes 12mm 4 Pin PWM RGB for Intel.',
    Cat: 'Electronics',
    Price: '156',
    Img: './assets/tp6.png',
  },
  {
    id: 7,
    Title: 'Playstation 4 2TB Slim Gaming Console.',
    Cat: 'Gaming',
    Price: '$2098',
    Img: './assets/tp7.jpg',
  },
  {
    id: 8,
    Title: 'Mini Portable Mobile Phone Powerbank for iphone.',
    Cat: 'Electronics',
    Price: '$386',
    Img: './assets/tp8.jpg',
  },
  {
    id: 9,
    Title: 'Microsoft Surface pro 8-13 Touchscreen.',
    Cat: 'Tablet',
    Price: '$986',
    Img: './assets/p9.jpg',
  },
  {
    id: 10,
    Title: 'Gaming BoomBox Headset .',
    Cat: 'Gaming',
    Price: '$286',
    Img: './assets/p10.jpg',
  },
  {
    id: 11,
    Title: 'Echo Show 5(2nd Gen)Adjustable Stand Charcoal.',
    Cat: 'Electronics',
    Price: '$86',
    Img: './assets/p11.jpg',
  },
  {
    id: 12,
    Title: 'Echo Dot smart speaker.',
    Cat: 'Electronics',
    Price: '$186',
    Img: './assets/p12.jpg',
  },
];

export default Productdetail;
